services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
    ports:
      - '3306:3306'
    volumes:
      - ./backend/bibliotekaPHP/:/var/www/html/api/
      - ./backend/bibliotekaPHP/book_covers:/var/www/html/book_covers
      - ./backend/bibliotekaPHP/mojprojekt:/var/www/html/api/mojprojekt
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_app
    ports:
      - '80:80'
    environment:
      DB_HOST: mysql
      DB_NAME: library
      DB_USER: library_user
      DB_PASS: library_pass
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/bibliotekaPHP/:/var/www/html/api/
      - ./backend/bibliotekaPHP/book_covers:/var/www/html/book_covers
    links:
      - mysql:mysql
volumes:
  mysql_data:
